### ISSUE TITLE
Support python 3

### ISSUE THREAD

**Issue by pybokeh** [Falkonry/falkonry-python-client#9]
Hi I'm using Python 3.4.  Not sure if this Python client supports Python 3.x or not, but anyways got the following error message, when running the following lines:  

``` python
from falkonryclient import client as Falkonry
from falkonryclient import schemas as Schemas

falkonry   = Falkonry('https://service.falkonry.io', 'my_auth_token')
```

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-eae7303cdc03> in <module>()
----> 1 from falkonryclient import client as Falkonry
      2 from falkonryclient import schemas as Schemas
      3 
      4 falkonry   = Falkonry('https://service.falkonry.io', 'my_auth_token')

/home/pybokeh/envs/jupyter/lib/python3.4/site-packages/falkonryclient/__init__.py in <module>()
     15 
     16 """
---> 17 from falkonryclient.helper import schema as schemas
     18 from falkonryclient.service import falkonry
     19 

/home/pybokeh/envs/jupyter/lib/python3.4/site-packages/falkonryclient/helper/schema.py in <module>()
      9 """
     10 
---> 11 from falkonryclient.helper.models import *
     12 
     13 Models = {

/home/pybokeh/envs/jupyter/lib/python3.4/site-packages/falkonryclient/helper/models/__init__.py in <module>()
----> 1 from Assessment import Assessment
      2 from Pipeline import Pipeline
      3 from Signal import Signal
      4 from Eventbuffer import Eventbuffer
      5 from Subscription import Subscription  

ImportError: No module named 'Assessment'
```

**Comment by phagunbaya** [comment]
@pybokeh : Currently we only support python 2.7

**Comment by phagunbaya** [comment]
@pybokeh : Quick question - Can you please tell us more about the experiment you are trying to do ? This will help us to escalate this issue and support you by better mean.

**Comment by pybokeh** [comment]
Hello @phagunbaya 

I am trying to do a classification task to classify data into a categorical label.  I am currently using Python scikit-learn machine library to do this, but was also looking into using a local GUI application like KNIME or web GUI (cloud-based) environment to perform machine learning experiments.  I was referred to your fellow associate by my coworker who was looking into using Falkonry.

Here is my example use case:  
http://nbviewer.jupyter.org/gist/anonymous/d3979c313dcee8dc44ab3047f5610032

I am attempting to use the Falkonry web UI, but than came across this GitHub repo and thought perhaps I can do this all behind the scenes using Python.  I am currently trying to get familiar with the web UI.  Thanks for looking into supporting Python 3.  Otherwise, I can just create a virtual environment running Python 2.7.

**Comment by pybokeh** [comment]
@phagunbaya BTW, my data is not time-series based, so I received instructions via email from a Falkonry associate on how to transform/format the data so that it would work with Falkonry AI:

http://nbviewer.jupyter.org/gist/anonymous/70c3edc3424a91ad2ce6c54965ce537a

**Comment by phagunbaya** [comment]
@pybokeh Thanks for the elaboration. The steps seem fine to me but I would like to point out that, using this client library you can only create eventbuffer, pipeline and add data. For rest steps you might have to use the http APIs documented here: `https://service.falkonry.io/api` or use the Falkonry UI. 
We do have plan to include all the APIs in the client library but that's not targeted any sooner. Please let me know if you need anything and you can always drop an email with question at `support[at]falkonry[dot]com`.
